a=input("Your last name, first name? \n")
b=input("How old are you? \n")
c=input("Your phone number? \n")
print("Your first name, last name: ", a)
print("Your age: ", b)
print("Your phone number: ", c)
